---
- name: Nano installed test
  hosts: all
  become: true
  tasks:

- name: Install webmin dependencies.
  apt:
    pkg:
    - perl
    - libnet-ssleay-perl
    - openssl
    - libauthen-pam-perl
    - libpam-runtime
    - libio-pty-perl
    - apt-show-versions
    - python
- name: Install latest webmin .deb package.
  apt:
    deb: http://www.webmin.com/download/deb/webmin-current.deb
